# Generated by Django 4.0.5 on 2022-06-21 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_comuna_ante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_tipo_comuna_ante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_comuna_dado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_tipo_comuna_dado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_tipo_demanda', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='demanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.DateTimeField(blank=True, null=True)),
                ('detalle', models.CharField(max_length=1000)),
                ('rut_dado', models.CharField(max_length=10)),
                ('nombre_dado', models.CharField(max_length=40)),
                ('apellido_dado', models.CharField(max_length=40)),
                ('telefono_dado', models.CharField(max_length=12)),
                ('rut_dante', models.CharField(max_length=10)),
                ('nombre_dante', models.CharField(max_length=40)),
                ('apellido_dante', models.CharField(max_length=40)),
                ('telefono_dante', models.CharField(max_length=12)),
                ('comuna_dado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tipo_comuna_dado')),
                ('comuna_dante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tipo_comuna_ante')),
                ('tpo_dem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tipo_demanda')),
            ],
        ),
    ]
