# Generated by Django 4.0.5 on 2022-06-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='hora',
            field=models.DateField(blank=True, null=True),
        ),
    ]
